/*
MyOpenLab by Carmelo Salafia www.myopenlab.de
Copyright (C) 2004  Carmelo Salafia cswi@gmx.de
Copyright (C) 2023 Subhraman Sarkar (Modifications)
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package VisualLogic.gui;

import VisualLogic.Tools;
import VisualLogic.Settings;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.io.File;
import javax.swing.*;
import javax.swing.border.MatteBorder;
import javax.swing.border.TitledBorder;


/**
 *
 * @author  Homer
 */
public class DialogOptions extends JDialog
{    
    private Settings settings;    
    private final FrameMain frameMain;
	private JTextField txtProjectPath;
	private JTextField txtConfigPath;
	private JTextField txtElementPath;
    
    /** Creates new form frmOptions */
    public DialogOptions(Settings settings, FrameMain parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        
        jCheckBox5.setVisible(false);
        
        this.frameMain = parent;
        
        this.settings = settings;
        
        txtUserdefPath.setText(settings.getUserdefinedElementsPath());
        
        int rx1 = settings.getCircuitRasterX();
        int ry1 = settings.getCircuitRasterY();
        
        int rx2 = settings.getFrontRasterX();
        int ry2 = settings.getFrontRasterY();

        
        SpinnerNumberModel modelA2 = new SpinnerNumberModel( rx1, 1.0, 100.0, 1 );
        SpinnerNumberModel modelB2 = new SpinnerNumberModel( ry1, 1.0, 100.0, 1 );
        
        jSpinner5.setModel(modelA2);
        jSpinner6.setModel(modelB2);
        
        SpinnerNumberModel modelA = new SpinnerNumberModel( rx2, 1.0, 100.0, 1 );
        SpinnerNumberModel modelB = new SpinnerNumberModel( ry2, 1.0, 100.0, 1 );
        
        jSpinner1.setModel(modelA);
        jSpinner2.setModel(modelB);
        
        
        java.awt.event.ActionListener actionListener = (java.awt.event.ActionEvent actionEvent) -> {
            dispose();
        };
        
        KeyStroke stroke = KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0);
        rootPane.registerKeyboardAction(actionListener, stroke, JComponent.WHEN_IN_FOCUSED_WINDOW);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

//        buttonGroup1 = new ButtonGroup();
        jTabbedPane1 = new JTabbedPane();
        jPanel3 = new JPanel();
        jPanel5 = new JPanel();
        jCheckBox2 = new JCheckBox();
        jCheckBox1 = new JCheckBox();
        jSpinner2 = new JSpinner();
        jSpinner1 = new JSpinner();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jPanel6 = new JPanel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jSpinner5 = new JSpinner();
        jSpinner6 = new JSpinner();
        jCheckBox3 = new JCheckBox();
        jCheckBox4 = new JCheckBox();
        jPanel2 = new JPanel();
        jButton4 = new JButton();
        txtHTMLEditor = new JTextField();
        jLabel2 = new JLabel();
        jLabel6 = new JLabel();
        txtGraphicEditor = new JTextField();
        jButton6 = new JButton();
        jLabel13 = new JLabel();
        txtJavascriptEditor = new JTextField();
        jButton7 = new JButton();
        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        txtUserdefPath = new JTextField();
        jButton3 = new JButton();
        jButton5 = new JButton();
        jPanel7 = new JPanel();
        jCheckBox5 = new JCheckBox();
        jCheckBox6 = new JCheckBox();
        jPanel9 = new JPanel();
        jLabel10 = new JLabel();
        jLabel11 = new JLabel();
        jLabel12 = new JLabel();
        txtRepositoryURL = new JTextField();
        txtRepositoryLoginUser = new JTextField();
        txtRepositoryLoginPassword = new JTextField();
        jLabel3 = new JLabel();
        txtProxyHost = new JTextField();
        jLabel9 = new JLabel();
        txtProxyPort = new JTextField();
        jButton1 = new JButton();
        jButton2 = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("VisualLogic/NOI18N/frmOptions"); // NOI18N
        setTitle(bundle.getString("Title")); // NOI18N
        setResizable(false);

        jPanel5.setBorder(BorderFactory.createTitledBorder(bundle.getString("DialogOptions.jPanel5.border.title"))); // NOI18N

        jCheckBox2.setText(bundle.getString("_Align_to_Raster")); // NOI18N
        jCheckBox2.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBox1.setText(bundle.getString("Raster_Visible")); // NOI18N
        jCheckBox1.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel4.setText(bundle.getString("RasterX")); // NOI18N

        jLabel5.setText(bundle.getString("RasterY")); // NOI18N

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jCheckBox1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(144, 144, 144))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                .addGroup(GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSpinner1, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE))
                                .addGroup(GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSpinner2)))
                            .addComponent(jCheckBox2))
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinner1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel6.setBorder(BorderFactory.createTitledBorder(bundle.getString("DialogOptions.jPanel6.border.title"))); // NOI18N

        jLabel7.setText(bundle.getString("RasterX")); // NOI18N

        jLabel8.setText(bundle.getString("RasterY")); // NOI18N

        jCheckBox3.setText(bundle.getString("Raster_Visible")); // NOI18N
        jCheckBox3.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBox4.setText(bundle.getString("_Align_to_Raster")); // NOI18N
        jCheckBox4.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox4.setMargin(new java.awt.Insets(0, 0, 0, 0));

        GroupLayout jPanel6Layout = new GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox3)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinner6)
                            .addComponent(jSpinner5, GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jSpinner5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jSpinner6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, 219, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab(bundle.getString("DialogOptions.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        jButton4.setText(bundle.getString("durchsuchen")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtHTMLEditor.setText(bundle.getString("DialogOptions.txtHTMLEditor.text")); // NOI18N

        jLabel2.setText(bundle.getString("HTML_Editor")); // NOI18N

        jLabel6.setText(bundle.getString("imageEditor")); // NOI18N

        txtGraphicEditor.setText(bundle.getString("DialogOptions.txtGraphicEditor.text")); // NOI18N

        jButton6.setText(bundle.getString("durchsuchen")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel13.setText(bundle.getString("javascript_editor")); // NOI18N

        txtJavascriptEditor.setText(bundle.getString("DialogOptions.txtJavascriptEditor.text")); // NOI18N

        jButton7.setText(bundle.getString("DialogOptions.jButton7.text")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtJavascriptEditor, GroupLayout.PREFERRED_SIZE, 347, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtHTMLEditor, GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtGraphicEditor, GroupLayout.PREFERRED_SIZE, 347, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHTMLEditor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(txtGraphicEditor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJavascriptEditor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jButton7))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(bundle.getString("Editoren"), jPanel2); // NOI18N

        jLabel1.setText(bundle.getString("DialogOptions.jLabel1.text")); // NOI18N

        txtUserdefPath.setText(bundle.getString("DialogOptions.txtUserdefPath.text")); // NOI18N

        jButton3.setText(bundle.getString("DialogOptions.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText(bundle.getString("DialogOptions.jButton5.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        /*
        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtUserdefPath, GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(jLabel1)
                    .addComponent(jButton5))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(txtUserdefPath, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(bundle.getString("DialogOptions.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N
        */

        jCheckBox5.setText(bundle.getString("DialogOptions.jCheckBox5.text")); // NOI18N
        jCheckBox5.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox5.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBox6.setText(bundle.getString("DialogOptions.jCheckBox6.text")); // NOI18N
        jCheckBox6.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox6.setMargin(new java.awt.Insets(0, 0, 0, 0));

        GroupLayout jPanel7Layout = new GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox5))
                .addContainerGap(453, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox6)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(bundle.getString("DialogOptions.jPanel7.TabConstraints.tabTitle"), jPanel7); // NOI18N

        jLabel10.setText(bundle.getString("DialogOptions.jLabel10.text")); // NOI18N

        jLabel11.setText(bundle.getString("DialogOptions.jLabel11.text")); // NOI18N

        jLabel12.setText(bundle.getString("DialogOptions.jLabel12.text")); // NOI18N

        txtRepositoryURL.setText(bundle.getString("DialogOptions.txtRepositoryURL.text")); // NOI18N

        txtRepositoryLoginUser.setText(bundle.getString("DialogOptions.txtRepositoryLoginUser.text")); // NOI18N

        txtRepositoryLoginPassword.setText(bundle.getString("DialogOptions.txtRepositoryLoginPassword.text")); // NOI18N

        jLabel3.setText(bundle.getString("DialogOptions.jLabel3.text")); // NOI18N

        txtProxyHost.setText(bundle.getString("DialogOptions.txtProxyHost.text")); // NOI18N

        jLabel9.setText(bundle.getString("DialogOptions.jLabel9.text")); // NOI18N

        txtProxyPort.setText(bundle.getString("DialogOptions.txtProxyPort.text")); // NOI18N

        GroupLayout jPanel9Layout = new GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtRepositoryLoginPassword, GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(34, 34, 34)
                            .addComponent(txtRepositoryLoginUser))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(txtRepositoryURL)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(txtProxyPort, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(txtProxyHost))))
                    .addComponent(jLabel3))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProxyHost, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtProxyPort, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtRepositoryURL, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtRepositoryLoginUser, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtRepositoryLoginPassword, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(bundle.getString("DialogOptions.jPanel9.TabConstraints.tabTitle"), jPanel9); // NOI18N
        
        /********* New Tabs, SS 2023 ************/
        // Paths tab
        JPanel pnlPaths = new JPanel();
        BoxLayout ppLayout = new BoxLayout(pnlPaths, BoxLayout.Y_AXIS);
        pnlPaths.setLayout(ppLayout);
        
        JPanel pnlElementPath = new JPanel();
        JLabel lblElementPath = new JLabel(bundle.getString("DialogOptions.lblElementPath.text"));
        txtElementPath = new JTextField(25);
        txtElementPath.setText(FrameMain.elementPath);
        JButton btnElementPath = new JButton("Browse...");
        btnElementPath.addActionListener(
        	e -> {
        		JFileChooser files = new JFileChooser();
        		files.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        		int status = files.showOpenDialog(this);
        		if (status == JFileChooser.APPROVE_OPTION) {
        			txtElementPath.setText(files.getSelectedFile().getAbsolutePath());
        		}
        	}
        );
        pnlElementPath.setLayout(new BoxLayout(pnlElementPath, BoxLayout.X_AXIS));
        pnlElementPath.add(lblElementPath);
        pnlElementPath.add(txtElementPath);
        pnlElementPath.add(btnElementPath);
        
        // User Defined Path panel, moved here.
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
        JPanel pnlUPath = new JPanel();
        pnlUPath.setLayout(new BoxLayout(pnlUPath, BoxLayout.X_AXIS));
        pnlUPath.add(jLabel1);
        pnlUPath.add(txtUserdefPath);
        pnlUPath.add(jButton3);
        
        JPanel pnlCopyButton = new JPanel();
        pnlCopyButton.setLayout(new FlowLayout(FlowLayout.LEFT));
        pnlCopyButton.add(jButton5);
        
        // Project Path
        JPanel pnlProjectPath = new JPanel();
        JLabel lblProjectPath = new JLabel(bundle.getString("DialogOptions.lblProjectPath.text"));
        txtProjectPath = new JTextField(25);
        txtProjectPath.setText(FrameMain.frm.getSavePath().toAbsolutePath().toString());
        JButton btnProjectPath = new JButton("Browse...");
        btnProjectPath.addActionListener(
        		e -> {
        			JFileChooser files = new JFileChooser();
        			files.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        			int status = files.showOpenDialog(this);
        			if (status == JFileChooser.APPROVE_OPTION) {
        				txtProjectPath.setText(files.getSelectedFile().getAbsolutePath());
        			}
        		}
        		);
        pnlProjectPath.setLayout(new BoxLayout(pnlProjectPath, BoxLayout.X_AXIS));
        pnlProjectPath.add(lblProjectPath);
        pnlProjectPath.add(txtProjectPath);
        pnlProjectPath.add(btnProjectPath);
        
        // Config files path
        JPanel pnlConfigPath = new JPanel();
        JLabel lblConfigPath = new JLabel(bundle.getString("DialogOptions.lblConfigPath.text"));
        txtConfigPath = new JTextField(25);
        txtConfigPath.setText(FrameMain.frm.getConfigPath().toString());
        JButton btnConfigPath = new JButton("Browse...");
        btnConfigPath.addActionListener(
            	e -> {
            		JFileChooser files = new JFileChooser();
            		files.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            		int status = files.showOpenDialog(this);
            		if (status == JFileChooser.APPROVE_OPTION) {
            			txtConfigPath.setText(files.getSelectedFile().getAbsolutePath());
            		}
            	}
            );
        pnlConfigPath.setLayout(new BoxLayout(pnlConfigPath, BoxLayout.X_AXIS));
        pnlConfigPath.add(lblConfigPath);
        pnlConfigPath.add(txtConfigPath);
        pnlConfigPath.add(btnConfigPath);
        
        pnlPaths.add(pnlElementPath);
        pnlPaths.add(pnlUPath);
        pnlPaths.add(pnlProjectPath);
        pnlPaths.add(pnlConfigPath);
        pnlPaths.add(pnlCopyButton);
        
        jTabbedPane1.addTab(bundle.getString("DialogOptions.pnlPaths.TabConstraints.tabTitle"), pnlPaths);
        
        // Themes tab
        JPanel pnlThemes = new JPanel();
        pnlThemes.setLayout(new BorderLayout());
        
        JRadioButton btnMetal = new JRadioButton("Metal");
        JRadioButton btnSystem = new JRadioButton("System");
        JRadioButton btnNimbus = new JRadioButton("Nimbus");
        JRadioButton btnMOLCustom = new JRadioButton("MyOpenLab Custom");
        
        switch(FrameMain.frm.themeNo) {
        case 1 : btnMetal.setSelected(true); break;
        case 2 : btnSystem.setSelected(true); break;
        case 3 : btnMOLCustom.setSelected(true); break;
        default : btnNimbus.setSelected(true); break;
        }
        
        ButtonGroup bgThemes = new ButtonGroup();
        bgThemes.add(btnMetal);
        bgThemes.add(btnNimbus);
        bgThemes.add(btnSystem);
//        bgThemes.add(btnMOLCustom);
        
        btnMetal.addActionListener(evt -> { FrameMain.frm.themeNo = 1; });
        btnNimbus.addActionListener(evt -> { FrameMain.frm.themeNo = 0; });
        btnSystem.addActionListener(evt -> { FrameMain.frm.themeNo = 2; });
        btnMOLCustom.addActionListener(evt -> { FrameMain.frm.themeNo = 3; });
               
        JPanel pnlButtons = new JPanel();
        BoxLayout vBoxLayout = new BoxLayout(pnlButtons, BoxLayout.Y_AXIS);
        pnlButtons.setLayout(vBoxLayout);
        pnlButtons.add(btnNimbus);
        pnlButtons.add(btnMetal);
        pnlButtons.add(btnSystem);
//        pnlButtons.add(btnMOLCustom);
        pnlButtons.setBorder(new TitledBorder(
				new MatteBorder(5, 5, 5, 5, new Color(0, 255, 255)), "Look and Feel", TitledBorder.LEADING, TitledBorder.TOP, null, Color.BLACK));

        pnlThemes.add(pnlButtons, BorderLayout.CENTER);
        jTabbedPane1.addTab(bundle.getString("DialogOptions.pnlThemes.TabConstraints.tabTitle"), pnlThemes);

        /***************************************/

        jButton1.setText(bundle.getString("Cancel")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(bundle.getString("OK")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSettings(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, 199, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        //setSize(new java.awt.Dimension(650, 289));
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String str=chooseFile(txtUserdefPath.getText(),true);
        if (str!=null)
        {
            txtUserdefPath.setText(str);
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String str=chooseFile(txtGraphicEditor.getText(),false);
        if (str!=null)
        {
            txtGraphicEditor.setText(str);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        String str = chooseFile(txtHTMLEditor.getText(), false);
        if (str != null)
        {
            txtHTMLEditor.setText(str);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    
    public String chooseFile(String path,boolean onlyDir)
    {
        JFileChooser chooser  = new JFileChooser();

        chooser.setCurrentDirectory(new File(path));
        if (onlyDir)
        {
            //chooser.setDialogType (chooser.OPEN_DIALOG); 
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        }
        
        int returnVal = chooser.showOpenDialog(this);
        

        
        if(returnVal == JFileChooser.APPROVE_OPTION) 
        {
            return chooser.getSelectedFile().getAbsolutePath();          
        } 
        
        return null;
    }
    
    private void saveSettings(java.awt.event.ActionEvent evt)
    {
    	// Setting are saved to the settings Object,
    	// And then written to the config file config.xml,
    	// From the method saveConfigFile() in FrameMain.
        
        Double circuitDX = (Double)jSpinner5.getValue();
        Double circuitDY = (Double)jSpinner6.getValue();

        Double frontDX = (Double)jSpinner1.getValue();
        Double frontDY = (Double)jSpinner2.getValue();
        //owner.getFrontBasis().setRaster(x.intValue(),y.intValue());
        
        settings.setProxy_host(txtProxyHost.getText());
        settings.setProxy_port(txtProxyPort.getText());
        
        settings.setCircuitRasterOn(jCheckBox3.isSelected());
        settings.setCircuittAlignToGrid(jCheckBox4.isSelected());
        settings.setCircuitRasterX((int)circuitDX.doubleValue());
        settings.setCircuitRasterY((int)circuitDY.doubleValue());
                
        settings.setFrontRasterOn(jCheckBox1.isSelected());
        settings.setFrontAlignToGrid(jCheckBox2.isSelected());
        settings.setFrontRasterX((int)frontDX.doubleValue());
        settings.setFrontRasterY((int)frontDY.doubleValue());
        
        settings.setCircuitCrossVisible(jCheckBox5.isSelected());
        
        //settings.javaEditor=txtJavaEditor.getText();
        settings.setHTMLEditor(txtHTMLEditor.getText());
        //settings.jdkBin=txtJDKBIN.getText();
        settings.setGraphicEditor(txtGraphicEditor.getText());
                
        settings.setElementIDVisible(jCheckBox6.isSelected());
        
        String userPath = txtUserdefPath.getText();
        if (!settings.getUserdefinedElementsPath().equalsIgnoreCase(userPath))
        {
            frameMain.createUserElementSubDirs(txtUserdefPath.getText());
          //settings.userdefinedElementsPath=txtUserdefPath.getText();    
        }
            
        settings.setRepository_domain(txtRepositoryURL.getText());
        settings.setRepository_login_username(txtRepositoryLoginUser.getText());
        settings.setRepository_login_password(txtRepositoryLoginPassword.getText());
        
        settings.setJavascript_editor(txtJavascriptEditor.getText());
        
        Tools.userElementPath = settings.getUserdefinedElementsPath();
        
        result = true;
        
        // Save paths from Paths Tab
        settings.setElementsPath(txtElementPath.getText());
        settings.setProjectSavePath(txtProjectPath.getText());
        
        /********* Theme Switch. SS 2023 *******/
        FrameMain.frm.themeSwitch();
        		
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        result = false;
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      frameMain.copyUserdefElements();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String str = chooseFile(txtJavascriptEditor.getText(), false);
        if (str != null)
        {
            txtJavascriptEditor.setText(str);
        }
    }//GEN-LAST:event_jButton7ActionPerformed
    
    public void execute(Settings settings)
    {
        this.settings = settings;
        
        txtRepositoryURL.setText(settings.getRepository_domain());
        txtRepositoryLoginUser.setText(settings.getRepository_login_username());
        txtRepositoryLoginPassword.setText(settings.getRepository_login_password());

        
        txtHTMLEditor.setText(settings.getHTMLEditor());
        txtGraphicEditor.setText(settings.getGraphicEditor());
        
        jCheckBox1.setSelected(settings.isFrontRasterOn());
        jCheckBox2.setSelected(settings.isFrontAlignToGrid());

        jCheckBox3.setSelected(settings.isCircuitRasterOn());
        jCheckBox4.setSelected(settings.isCircuittAlignToGrid());
        
        jCheckBox5.setSelected(settings.isCircuitCrossVisible());        
        jCheckBox6.setSelected(settings.isElementIDVisible());
        
        
        txtProxyHost.setText(settings.getProxy_host());
        txtProxyPort.setText(settings.getProxy_port());
        
        txtJavascriptEditor.setText(settings.getJavascript_editor());
        
        setVisible(true);        
    }
    
    public static boolean result = false;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private ButtonGroup buttonGroup1;
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JButton jButton4;
    private JButton jButton5;
    private JButton jButton6;
    private JButton jButton7;
    private JCheckBox jCheckBox1;
    private JCheckBox jCheckBox2;
    private JCheckBox jCheckBox3;
    private JCheckBox jCheckBox4;
    private JCheckBox jCheckBox5;
    private JCheckBox jCheckBox6;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JPanel jPanel7;
    private JPanel jPanel9;
    private JSpinner jSpinner1;
    private JSpinner jSpinner2;
    private JSpinner jSpinner5;
    private JSpinner jSpinner6;
    private JTabbedPane jTabbedPane1;
    private JTextField txtGraphicEditor;
    private JTextField txtHTMLEditor;
    private JTextField txtJavascriptEditor;
    private JTextField txtProxyHost;
    private JTextField txtProxyPort;
    private JTextField txtRepositoryLoginPassword;
    private JTextField txtRepositoryLoginUser;
    private JTextField txtRepositoryURL;
    private JTextField txtUserdefPath;
    // End of variables declaration//GEN-END:variables
    
}
